export const voucherCreatedSuccessfully = "Voucher created successfully.";
export const anErrorOccurredWhileCreatingTheVoucher = " An error occurred while creating the  voucher.";
export const errorRetrievingVouchers = "Error retrieving vouchers.";
export const vouchersRetrievedSuccessfully = "Voucher details retrieve successfully.";
export const voucherCodeIsAlreadyExist = "Voucher code is already exist.";
export const voucherRecordNotFound = "Voucher record not found.";
export const voucherUpdatedSuccessfully = 'Voucher updated successfully.';
export const anErrorOccurredWhileUpdatingTheVoucher = "An error occurred while updating the voucher.";
export const errorDeletingVoucher = "Error deleting voucher";
export const voucherDeletedSuccessfully = "Voucher deleted successfully";
export const voucherNotFound = "Voucher not found";
export const voucherUpdateError = "Voucher update error";
export const voucherStatusUpdatedSuccessfully = "Voucher status updated successfully";
export const voucherNotFoundOrNoChangesHaveBeenMade = "Voucher not found or no changes have been made";
export const invalidStatusValueProvided = "Invalid status value provided";
export const notificationCreationFailed = "Notification creation failed:";
export const greatNews = "🎉 Hey";
export const aNewcouponhasJustBeenGeneratedFor = `! A new 🎟️ coupon has just been generated for`
export const theyCanRedeemitAtYourStoreSoGetReadyToWelcomeThemWithASmile = ` They can redeem it at your store 🛍️, so get ready to welcome them with a smile 😊!`
export const fileNotUpload = "File not upload";
export const failedToSendEmails = "Failed to send emails.";
export const failedToUpdateThePDFURLInTheDatabase = "Failed to update the PDF URL in the database.";